In [1]:
import numpy as np
import pandas as pd

<span style="color:orange"><b>json data</b></span>

In [3]:
df = pd.read_json('train.json')
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

**Fetching json data from url**

In [4]:
df = pd.read_json('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day16%20-%20working-with-json-and-sql/train.json')
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

<span style="color:orange"><b>Fetching sql data</b></span>

In [6]:
!python -m pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\naren\onedrive\documents\desktop\new folder\lib\site-packages (9.6.0)

In [7]:
import mysql.connector

In [8]:
conn = mysql.connector.connect(host="localhost",port=3306,user="root",password="@Narendra07", database="world")

In [23]:
df = pd.read_sql_query("SELECT * FROM city", conn)

C:\Users\naren\AppData\Local\Temp\ipykernel_23652\2626035173.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM city", conn)

In [24]:
df

      ID              Name CountryCode        District  Population
0      1             Kabul         AFG           Kabol     1780000
1      2          Qandahar         AFG        Qandahar      237500
2      3             Herat         AFG           Herat      186800
3      4    Mazar-e-Sharif         AFG           Balkh      127800
4      5         Amsterdam         NLD   Noord-Holland      731200
5      6         Rotterdam         NLD    Zuid-Holland      593321
6      7              Haag         NLD    Zuid-Holland      440900
7   4060      Santa Monica         USA      California       91084
8   4061        Fall River         USA   Massachusetts       90555
9   4062           Kenosha         USA       Wisconsin       89447
10  4063             Elgin         USA        Illinois       89408
11  4064            Odessa         USA           Texas       89293
12  4065            Carson         USA      California       89089
13  4066        Charleston         USA  South Carolina       89063
14  4067  Charlotte Amalie         VIR       St Thomas       13000
15  4068            Harare         ZWE          Harare     1410000
16  4069          Bulawayo         ZWE        Bulawayo      621742
17  4070       Chitungwiza         ZWE          Harare      274912
18  4071      Mount Darwin         ZWE          Harare      164362
19  4072            Mutare         ZWE      Manicaland      131367
20  4073             Gweru         ZWE        Midlands      128037
21  4074              Gaza         PSE            Gaza      353632
22  4075        Khan Yunis         PSE      Khan Yunis      123175
23  4076            Hebron         PSE          Hebron      119401
24  4077          Jabaliya         PSE      North Gaza      113901
25  4078            Nablus         PSE          Nablus      100231
26  4079             Rafah         PSE           Rafah       92020

In [27]:
df = pd.read_sql_query("SELECT * FROM city WHERE District LIKE 'Harare' ", conn)

C:\Users\naren\AppData\Local\Temp\ipykernel_23652\501137620.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM city WHERE District LIKE 'Harare' ", conn)

In [28]:
df

     ID          Name CountryCode District  Population
0  4068        Harare         ZWE   Harare     1410000
1  4070   Chitungwiza         ZWE   Harare      274912
2  4071  Mount Darwin         ZWE   Harare      164362